### ISSUE TITLE
gpd fan has stopped working

### ISSUE THREAD

**Issue by parkerlreed** [njkli/gpd-fan#2]
I was having the occasional system lock up and couldn't figure out what was going on. Turns out every 4 seconds the gpd-fan.service tried to start, failed, repeat.

Arch Linux

````
[parker@gpdpocket browsers]$ sudo gpd-fan 
Error writing file: Device or resource busy (Errno)
Failed to raise an exception: END_OF_STACK
[0x55c5953bb176] ???
[0x55c5953721f7] __crystal_raise +455
[0x55c59537427c] ???
[0x55c59537fb90] ???
[0x55c5953785d5] ???
[0x55c595377636] ???
[0x55c59538f227] main +327
[0x7f1c24b90f4a] __libc_start_main +234
[0x55c59536d9da] _start +42
[0x0] ???
````

**Comment by voobscout** [comment]
This repo is obsolete, use kernel provided in njkli/gpg-pocket, it has native support for this device, ie, modprobe gpd-fan or something similar. I suspect this implementation fails, because it conflicts with newer kernels by Hans.

**Comment by parkerlreed** [comment]
@voobscout Ahh thanks. I see it loaded that module by default (gpd-pocket-fan) but it never seems to kick on under load. Do I just need to play with the parameters?
